id: face_tracking
name: face_tracking
name[zh]: 人脸追踪
version: 1.0.2
author: Sipeed Ltd
icon: assets/face_tracking.png
desc: Face tracking with MaixCAM and gimbal.
desc[zh]: 使用 MaixCAM 和云台进行人脸跟踪。
files:
  - app.yaml
  - assets
  - README.md
  - face_tracking
