id: local_chat
name: Local Chat
name[zh]: 本地聊天
version: 1.0.0
icon: assets/icon.json
author: Sipeed Ltd
desc: Local AI Chat
desc[zh]: 本地AI 聊天
exclude:
  - dist
  - build
  - .gitignore
files:
  - assets
  - app.yaml
  - main.py
  - README.md
