id: ai_chat
name: AI Chat
name[zh]: AI聊天
version: 1.0.3
icon: assets/icon.json
author: Sipeed Ltd
desc: AI Chat
desc[zh]: AI 聊天
exclude:
  - dist
  - build
  - .gitignore
files:
  - assets
  - app.yaml
  - main.py
  - README.md
